Update data.toml to include cloud sync auto response
castdrian/autosupport pull request #12
Opened 2024-07-25 13:01 UTC by Rairof

2024-07-25 13:07 UTC, nexpid requested changes

2024-07-25 13:07 UTC, nexpid commented on src/data.toml
> +cloudsync_not_working = "You might be using a outdated version of cloud sync as older versions and vendetta version doesn't work anymore-\n- check pins and install latest cloud sync (https://bunny.ne
```suggestion
cloudsync_not_working = "You might be using an outdated version of Cloud Sync, as older versions don't work anymore.\n1. Make sure you have the latest version of Cloud Sync (available in the pins) available\n2. If that doesn't work, and you have **antied** installed, uninstall and reinstall it (https://angelix1.github.io/MP/angel/antied/)"
```

2024-07-25 13:09 UTC, Rairof commented
do not merge, adding more auto responses

2024-07-25 13:56 UTC, Rairof commented
@castdrian review changes pls

2024-07-29 10:42 UTC, closed without merging

2024-07-29 10:42 UTC, Rairof commented
Added PR to pyoncord auto support fork